trigger:
  branches:
    include:
      - master

pool:
  name: pkdgpool

variables:
- group: subscription # Variable group containing ARM_SUBSCRIPTION_ID and other secrets
- name: ARM-SUBSCRIPTION-ID
  value: $[variables.ARMSUBSCRIPTIONID]

stages:
  - stage: initandplan
    displayName: "Terraform Init and Plan"
    jobs:
      - job: initplan
        displayName: "Initialize and Plan Terraform"
        steps:
        # Step 1: Export Environment Variables
        - task: PowerShell@2
          displayName: "Export Environment Variables"
          inputs:
            targetType: 'inline'
            script: |
              echo "Setting ARM_SUBSCRIPTION_ID environment variable"
              env:ARM_SUBSCRIPTION_ID = "$(ARM_SUBSCRIPTION_ID)"
              Write-Host "ARM_SUBSCRIPTION_ID set successfully."

        # Step 2: Terraform Init
        - task: TerraformTaskV4@4
          displayName: "Terraform Init"
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
            backendServiceArm: 'pkagent' # Azure DevOps Service Connection
            backendAzureRmResourceGroupName: 'dev-rg1'
            backendAzureRmStorageAccountName: 'devstgacbk01'
            backendAzureRmContainerName: 'devcont'
            backendAzureRmKey: 'dev.terraform.tfstate'

        # Step 3: Terraform Plan
        - task: TerraformTaskV4@4
          displayName: "Terraform Plan"
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
            commandOptions: '-out=tfplan'