trigger:
  branches:
    include:
      - master

pool:
  name: pkdgpool

variables:
- group: subscription # Variable group containing ARM_SUBSCRIPTION_ID and other secrets
- name: ARMSUBSCRIPTIONID
  value: $[variables.ARMSUBSCRIPTIONID]

stages:
  - stage: initandplan
    displayName: "Terraform Init and Plan"
    jobs:
      - job: tfsecscan
        displayName: tfsec scan
        steps:
        - task: tfsec@1
          inputs:
            version: 'v1.26.0'
            dir: '$(System.DefaultWorkingDirectory)/env/dev'
      - job: initplan
        displayName: "Initialize and Plan Terraform"
        steps:
        # Step 1: Export Environment Variables
        - task: PowerShell@2
          displayName: "Export Environment Variables"
          inputs:
            targetType: 'inline'
            script: |
              echo "Setting ARM_SUBSCRIPTION_ID environment variable"
              echo $(ARMSUBSCRIPTIONID)
              Write-Host "ARMSUBSCRIPTIONID set successfully."

        # Step 2: Terraform Init
        - task: TerraformTaskV4@4
          displayName: "Terraform Init"
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
            backendServiceArm: 'pkagent' # Azure DevOps Service Connection
            backendAzureRmResourceGroupName: 'dev-rg1'
            backendAzureRmStorageAccountName: 'devstgacbk01'
            backendAzureRmContainerName: 'devcont'
            backendAzureRmKey: 'dev.terraform.tfstate'

        # Step 3: Terraform Plan
        - task: TerraformTaskV4@4
          displayName: "Terraform Plan"
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
            environmentServiceNameAzureRM: 'pkagent'

        # step 4: Manuall intervention
  - stage: Terraformapply
    displayName: terraform apply
    jobs:
      - job: malualapprovaljob
        displayName: manual approval job
        pool: server
        steps:
        - task: ManualValidation@1
          inputs:
            notifyUsers: 'prashant@gmail.com'
            instructions: 'Kindly approve'
      - job: terraformapply
        displayName: terraform apply
        steps:
        - task: TerraformTaskV4@4
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
            environmentServiceNameAzureRM: 'pkagent'